name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        node-version: [18.x]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3
      name: Install pnpm
      id: pnpm-install
      with:
        version: latest
        run_install: |
          - recursive: false
            args: [--no-frozen-lockfile]

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
        cache: pnpm

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Build
      env:
        CI: true
      run: pnpm build
